FROM arm64v8/python:3.7-alpine3.8

RUN apk add \
        build-base \
        libffi-dev \
        libressl-dev

ADD dist/ /dist
RUN pip install --no-cache-dir dist/*.whl

WORKDIR /rproxy
ENTRYPOINT ["python", "-m", "twisted", "--log-format=text"]
CMD ["rproxy"]

